name: Docker Image CI

on:
  push:
    branches:
      - master
      - dev
  release:
    types: [published]

jobs:
  build:
    if: ${{ github.repository == 'BC-SECURITY/Empire' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: bcsecurity/empire
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          tag_names: true